name: Publish
on:
  push:
    tags:
      - '*.*.*.*'
jobs:
  Build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: true
      
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          
      - name: Get Environment Variables
        run: |
          $tag = "${{ github.ref }}" -replace 'refs/tags/', ''

          "tag=$tag" | Out-File -Append -FilePath $Env:GITHUB_ENV
          
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Download Dalamud Latest
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip -DestinationPath "$env:AppData\XIVLauncher\addon\Hooks\dev"

      - name: Restore Nuget Packages for RSR
        run: dotnet restore RotationSolver/RotationSolver.csproj

      - name: Build Plugin
        run: dotnet build --no-restore -c Release RotationSolver/RotationSolver.csproj -p:AssemblyVersion=${{ env.tag }} -p:FileVersion=${{ env.tag }} -p:PackageVersion=${{ env.tag }} -p:InformationalVersion=${{ env.tag }} --output .\build

      - name: Zip Plugin
        run: Compress-Archive -Path .\build\* -DestinationPath .\build\RotationSolver.zip

      - name: Publish Plugin
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/RotationSolver.zip
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Doc Gen Tool
        run: |
          dotnet pack -c Release RotationSolver.DocumentationGenerator/RotationSolver.DocumentationGenerator.csproj
          dotnet tool restore --add-source RotationSolver.DocumentationGenerator/nupkg
      - name: Build Docs
        run: dotnet tool run docgen build/RotationSolver.Basic.xml build/RebornRotations.xml
      - name: Publish Docs
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: _doc/
          commit-message: Update wiki to ${{ env.tag }}